services:

  web:
    build:
      context: ./django/
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose:
     - 8000
    # env_file:
    #   - ./.env/dev.env

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      # - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/templates/:/etc/nginx/templates
      - static_files:/home/app/staticfiles
    env_file:
       - ./.env/dev.env
       
volumes:
  static_files: